CREATE TABLE navbar_items(
id SERIAL PRIMARY KEY,
title VARCHAR(100) NOT NULL,
url VARCHAR(300) NOT NULL,
display_order INT NOT NULL DEFAULT 0,
is_btn  BOOLEAN DEFAULT FALSE,
is_active BOOLEAN DEFAULT FALSE
);